// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCvkcaRhQ7ONhHjP0uHRLKYVakFw0EQWcA',
    appId: '1:834191099253:web:a74efd06b9ac3b92ad3f3c',
    messagingSenderId: '834191099253',
    projectId: 'united-strategy-351123',
    authDomain: 'united-strategy-351123.firebaseapp.com',
    databaseURL: 'https://united-strategy-351123-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'united-strategy-351123.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBOY6GqKAWqrjqgcr8xtnQbOgu6Scjk6h8',
    appId: '1:834191099253:android:b4d359ddb0a2c2b4ad3f3c',
    messagingSenderId: '834191099253',
    projectId: 'united-strategy-351123',
    databaseURL: 'https://united-strategy-351123-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'united-strategy-351123.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA_-dAjES_npNclNerun-H_38qULWuGibk',
    appId: '1:834191099253:ios:69c11da110444fa2ad3f3c',
    messagingSenderId: '834191099253',
    projectId: 'united-strategy-351123',
    databaseURL: 'https://united-strategy-351123-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'united-strategy-351123.appspot.com',
    iosClientId: '834191099253-ltjkltg710eolt02to09l7nr0ajtddn4.apps.googleusercontent.com',
    iosBundleId: 'com.example.modul12',
  );
}
